### ISSUE TITLE
Nuxt typed router nuxtconfig error (since v2.3.0)

### ISSUE THREAD

**Issue by ThimoDEV** [victorgarciaesgi/nuxt-typed-router#66] opened 2023-02-08 21:35 UTC
Since version 2.3.0 I get the following error in my nuxt config: 

Type instantiation is excessively deep and possibly infinite

![image](https://user-images.githubusercontent.com/68739517/217656248-d78e055d-f960-41b9-9295-968cd587e7ca.png)

I used nuxt v3.1.2 for this. It also happened in version 3.1.1

**Comment by victorgarciaesgi** [comment] 2023-02-09 12:19
Hi! It's weird, are you sure it's related to nuxt-typed-router? 
Did you run nuxt prepare? 
Do you have a reproduction? :)

**Comment by ThimoDEV** [comment] 2023-02-09 12:35
When I removed nuxt-typed-router it solved the issue yes. I can get you a reproduction later this day :)

**Comment by victorgarciaesgi** [comment] 2023-02-09 15:19
Yep I would love to! I can't reproduce it with any of internal projects.
Is the error style here if there is no other module present?

**Comment by ThimoDEV** [comment] 2023-02-09 21:23
https://github.com/ThimoDEV/nuxt3-tailwind-warning-content/tree/nuxt-hydrated-error

Don't mind the repo name, I used it for other issues I encountered. This repo has only nuxt and nuxt typed router. After yarn install I get the error

**Comment by victorgarciaesgi** [comment] 2023-02-10 11:24
I reproduce it without installing `nuxt-typed-router`, seems like either a problem with `@nuxtjs/tailwindcss` or a config problem
![image](https://user-images.githubusercontent.com/15092120/218081070-eb483cb5-65aa-4194-b7c8-244b81a3c8e8.png)

**Comment by Shab0x** [comment] 2023-02-10 17:16
Hi there!

Got the same problem since i upgraded nuxt to last versions (tried with v3.1.* and v3.2)

I tried to reproduce it in a stackblitz env, declaring tailwindcss as a modules appears to be ok... that is not the case of nuxt-typed-router.

[Reproduction link](https://stackblitz.com/edit/nuxt-starter-ccv2rw?file=package.json,nuxt.config.ts)

**Comment by victorgarciaesgi** [comment] 2023-02-10 17:35
Thanks for the repro! I will investigate, but I think It's related to Nuxt types :(

**Comment by victorgarciaesgi** [comment] 2023-02-10 17:35
Have you tried with `3.2.0` ?

**Comment by Shab0x** [comment] 2023-02-10 17:50
Yes, think so. The issue appears when we upgrade from `3.0.0`...
As I said, tried with `3.1.*` & `3.2.0` (both locally and on stackblitz)

Btw you're the only one who provide type-safe routing in Nuxt/Vue env. 
So thanks for that.

**Comment by victorgarciaesgi** [comment] 2023-02-10 17:52
Thanks! :D 
And can't reproduce it with my playground 😩 
https://stackblitz.com/edit/github-7e4xvw?file=nuxt.config.ts

(BTW I have path autocomplete nearly ready for a next version)

**Comment by victorgarciaesgi** [comment] 2023-02-10 18:04
I may have something I will test on the beta channel

**Comment by victorgarciaesgi** [comment] 2023-02-10 18:08
Ok you can test with `v2.3.4`, it should be fixed! 
Thanks again for reporting :)

**Closed** 2023-02-10 18:08 UTC

**Comment by ThimoDEV** [comment] 2023-02-10 18:48
I just tried it with the latest nuxt version and the latest nuxt typed router release and its working on my end. Thanks for the quick fix! <3
